### ISSUE TITLE
Failed to fetch [Windows] [0.11.3]

### ISSUE THREAD

**Issue by XNiadl** [chaiNNer-org/chaiNNer#803] opened 2022-08-21 13:41 UTC
-OS: Windows 10,
-Version: Alpha v0.11.3
-GPU: AMD 

**Description**
Open chaiNNer 
Wait for it to load
--> Error 
Tried deleting the folder and reopen, without any success.

Log has been attached 
[main.log](https://github.com/joeyballentine/chaiNNer/files/9389196/main.log)

**Comment by joeyballentine** [comment] 2022-08-21 13:45
Looks like there's an issue loading the cv2 library. Can you delete the python folder from application support/chainner and try again?

**Comment by XNiadl** [comment] 2022-08-21 14:13
> Looks like there's an issue loading the cv2 library. Can you delete the python folder from application support/chainner and try again?

Same issue. New log:  
[main.log](https://github.com/joeyballentine/chaiNNer/files/9389272/main.log)

**Comment by joeyballentine** [comment] 2022-08-21 14:59
Try following this answer, but with the python located in chaiNNer's application support folder

https://stackoverflow.com/questions/69159475/open-cv-module-cannot-be-imported

**Comment by XNiadl** [comment] 2022-08-22 18:10
Doesn't work. Still get the same error.
[main.log](https://github.com/joeyballentine/chaiNNer/files/9396628/main.log)

**Comment by joeyballentine** [comment] 2022-08-22 18:15
I'm not sure what to do to fix it then. I'll do some more research and see if I can figure anything out

**Comment by joeyballentine** [comment] 2022-08-23 21:59
@XNiadl would you mind testing the [latest release](https://github.com/joeyballentine/chaiNNer/releases/tag/v0.11.4)?

**Comment by XNiadl** [comment] 2022-08-24 14:49
Before testing I uninstalled the pervious version. Then I downloaded the "Setup version x64" (correct right?) then opened with the same result. 

I tried the fix you linked to with no success :( 

[main.log](https://github.com/joeyballentine/chaiNNer/files/9417080/main.log)

**Comment by joeyballentine** [comment] 2022-08-24 15:08
Did you have an existing python installation and/or previously enable the "use system python"? The stuff I'm finding online about these errors seem to indicate that you have mismatching versions of opencv-python and opencv-python-headless. But chaiNNer only uses one of these so I'm not sure how that would be possible unless the issue is through your system python

**Comment by XNiadl** [comment] 2022-08-24 15:32
> Did you have an existing python installation and/or previously enable the "use system python"? The stuff I'm finding online about these errors seem to indicate that you have mismatching versions of opencv-python and opencv-python-headless. But chaiNNer only uses one of these so I'm not sure how that would be possible unless the issue is through your system python

I tried deleting everything related to python on my drive and it doesn't fix the issue. Haven't installed anything related to python that I know of, this is almost a clean install of windows.

**Comment by joeyballentine** [comment] 2022-08-24 16:08
@XNiadl when you uninstalled the previous version did you check to make sure the python folder was gone from the appdata/roaming/chaiNNer folder? 

Try deleting that (appdata/roaming/chainner/python) and seeing if on the next start it works

**Comment by XNiadl** [comment] 2022-08-24 16:31
> @XNiadl when you uninstalled the previous version did you check to make sure the python folder was gone from the appdata/roaming/chaiNNer folder?
> 
> Try deleting that (appdata/roaming/chainner/python) and seeing if on the next start it works

Nope I didn't. But I tried a few times to delete python before that. Tried again on the new release and still getting an error.

Also tried moving the content into a cv2 folder without luck. 


[main.log](https://github.com/joeyballentine/chaiNNer/files/9417865/main.log)

**Comment by joeyballentine** [comment] 2022-08-24 17:06
I have no idea why this wouldn't be working. There must be something about your system specifically that just prevents it from working properly.

Idea: Install python 3.9 to your system like normal. Then go to `AppData\Roaming\chaiNNer\settings` and create a new text file named 'use-system-python'. Open it in notepad, and type `true` into it, and save it. Then rename it and remove the .txt extension.

Chainner should then try using your system python instead of the integrated one. Maybe that one will be able to properly use opencv

**Comment by joeyballentine** [comment] 2022-08-24 19:36
https://github.com/opencv/opencv-python/issues/655 this is the same issue as you. Definitely seems to be the case that multiple different opencv variants are installed, somehow

**Comment by joeyballentine** [comment] 2022-10-20 22:29
@XNiadl were you ever able to get this to work?

**Comment by joeyballentine** [comment] 2024-02-28 01:20
Closing this as I do not believe it is still relevant

**Closed by joeyballentine** 2024-02-28 01:20 UTC
Labels: bug
