### ISSUE TITLE
F5 doesn't work at first

### ISSUE THREAD

**Issue by VikMorroHun** [chaiNNer-org/chaiNNer#1639] opened 2023-03-07 17:18 UTC
**Information:**

- Chainner version: 0.18.3
- OS: Windows 10, x64

**Description**
After loading a saved .chn file pressing F5 does nothing.  If I want to start upscaling the textures already in the proper folder I have to click on the Run (F5) icon at the top of the window.
On subsequent iterations F5 works as intended.

[logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/10912080/logs.zip)

**Comment by VikMorroHun** [comment] 2023-03-07 17:59
Restarted ChaiNNer, loaded a .chn file, pressed F5 - it works.  Possible false report.

**Comment by RunDevelopment** [comment] 2023-03-07 21:57
This might have been because selected some input element (e.g. a text box, or the app menu) that swallowed the input. Anyway, this is certainly a bug. 

If you get to reproduce it again, try to press a letter keys or the arrow keys so see whether some input has been selected. This should give us a hit as to what is causing this.

**Comment by queridaalexa** [comment] 2023-03-07 22:32
Thank you for the update, and for resolving the issue. As a beginner in this subject and an illustrator, I appreciate the community's efforts to help each other and maintain a high level of quality in the project. I look forward to following the discussion and learning more. thanks ;))

**Comment by stonerl** [comment] 2023-08-18 07:44
This happens when the focus is on an input field:

![CleanShot 2023-08-18 at 09 43 23@2x](https://github.com/chaiNNer-org/chaiNNer/assets/2091312/3f8fb3a9-2bbb-4614-8095-507bdf6318b3)

![CleanShot 2023-08-18 at 09 44 48@2x](https://github.com/chaiNNer-org/chaiNNer/assets/2091312/fd6defb0-6cb5-4d44-876a-8653ea8064c6)

**Closed** 2023-08-22 13:40 UTC
Labels: bug
