### ISSUE TITLE
Small delay (0.3 seconds) after each video frame processing

### ISSUE THREAD

**Issue by gabriele2000** [chaiNNer-org/chaiNNer#1656] opened 2023-03-14 22:23 UTC
**Information:**

- Chainner version: 0.18.3
- OS: Pop!_Os 22.04

**Description**
I'm upscaling a movie, I'm using a model that takes only 0.4 seconds each frame (700x300 source, 4x upscaling) but for some reason between one frame and another there is this small delay (the animations and the image preview gives it away).
Now the total time for each frame is something from 0.6 and 0.8 seconds: that delay makes batch processing and video upscaling inefficient time-wise.

**Logs**
[logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/10974357/logs.zip)

**Comment by RunDevelopment** [comment] 2023-06-19 12:26
I did some performance optimizations, which were released in [v0.18.7](https://github.com/chaiNNer-org/chaiNNer/releases/tag/v0.18.7). This likely isn't an issue anymore, so I'm going to close this now. If the issue is still present, please comment and I will reopen this.

**Closed by RunDevelopment** 2023-06-19 12:26 UTC
Labels: bug
