### ISSUE TITLE
Error report: Object has been destroyed

### ISSUE THREAD

**Issue by ozzanon** [chaiNNer-org/chaiNNer#1700] opened 2023-04-05 12:22 UTC
```
UnhandledRejection TypeError: Object has been destroyed
```
ChaiNNer: chaiNNer 0.18.4
OS: macOS 10.18

**Comment by joeyballentine** [comment] 2023-04-05 13:17
Duplicate of #1665 and #1691. I thought this was just a windows NT thing but i guess not. 

For the devs: https://stackoverflow.com/questions/38309240/object-has-been-destroyed-when-open-secondary-child-window-in-electron-js

Seems like we try to show a window that never actually gets created or something. We probably should have some kind of better error handling for that.

**Closed** 2023-04-09 12:39 UTC
