### ISSUE TITLE
new error from v0.18.4

### ISSUE THREAD

**Issue by li1i9** [chaiNNer-org/chaiNNer#1705] opened 2023-04-05 22:05 UTC
ChaiNNer version: v0.18.4
OS: Windows 10 Home

Hello Support

I hope this message finds you well. I am writing to report an issue I am encountering with your chaiNNer implementation of the U-2 Net ONNX model for background removal, specifically the transition from v0.18.3 to v0.18.4.
Prior to updating to v0.18.4, the background removal functionality using u2net.onnx was working perfectly in v0.18.3. However, after updating to the latest version, I started experiencing an error when running the background remover, preventing the process from completing successfully.
Would you kindly provide assistance in resolving this problem? If you require additional information about the error, my setup, or any other details, please let me know, and I would be happy to provide it.

Thank you in advance for your time and support.

Best regards,
Mishel.

Render log is empty, that's why I send only the main log and screenshots.
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11163437/main.log)
![337040403_1827227487673398_8151745758062993048_n](https://user-images.githubusercontent.com/128749309/230222072-7696ac3a-dcaf-4c4f-a3b3-a512e61d859b.png)
![338331825_909656266935791_3575477525512487475_n](https://user-images.githubusercontent.com/128749309/230222076-4ee59b18-e242-47bb-8682-22352d9f1b25.png)

**Comment by theflyingzamboni** [comment] 2023-04-05 22:07
This is a known bug caused by a check added to image outputs. I have it fixed in a branch I'm working on to add ISNET support.

**Comment by li1i9** [comment] 2023-04-05 22:16
ty a lot :)

**Comment by joeyballentine** [comment] 2023-04-06 15:50
Fixed in 0.18.5

**Closed by joeyballentine** 2023-04-06 15:50 UTC
Labels: bug
