### ISSUE TITLE
hidden icons menu is getting overloaded by Chainner icons

### ISSUE THREAD

**Issue by DeBlue7** [chaiNNer-org/chaiNNer#2711] opened 2024-03-26 23:39 UTC
- Chainner version:  0.22.2
- OS: Windows 10

**Description**
It is easier explained by this screenshot 
![Screenshot_20240327_003101_Moonlight](https://github.com/chaiNNer-org/chaiNNer/assets/104231514/3ee5e163-42ef-41f2-8667-77acbc0e41a1)

It is absolutely bonkers, and I feel as if it slows my PC down

**Comment by joeyballentine** [comment] 2024-03-26 23:47
Did this happen with previous versions? And are you sure those are from chaiNNer? The icon doesn't look right

**Comment by DeBlue7** [comment] 2024-03-27 00:34
This has been with previous versions yes.Well I guess you are right, because when I uninstalled chaiNNer, the icons were still there. But now I have no where they are from...

**Comment by joeyballentine** [comment] 2024-04-07 21:21
Closing this as it does not seem to actually be caused by chainner

**Closed by joeyballentine** 2024-04-07 21:21 UTC
Labels: bug
