### ISSUE TITLE
Error report: Object has been destroyed

### ISSUE THREAD

**Issue by Autantpourmoi** [chaiNNer-org/chaiNNer#2062] opened 2023-08-06 17:38 UTC
```
UnhandledRejection TypeError: Object has been destroyed

    at click (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:521013)
```
ChaiNNer: chaiNNer 0.19.0
OS: macOS 10.18

**Comment by joeyballentine** [comment] 2023-08-06 18:05
Duplicate of #1752

**Comment by joeyballentine** [comment] 2023-08-06 18:06
We believe this to be an issue with MacOS compatibly mode. I think once we get actual arm64 builds this should no longer be an issue

**Closed by joeyballentine** 2023-08-06 18:05 UTC
