### ISSUE TITLE
SCUNet noise leftovers

### ISSUE THREAD

**Issue by Wurlit** [chaiNNer-org/chaiNNer#2169] opened 2023-08-30 12:50 UTC
It could be a model issue, but I post the issue here just in case, because all the images I've seen online so far do not exhibit this flaw. Also, I don't see any answers from the author of SCUNet for a yer. Anyway, here are my results with scunet_color_real_gan and scunet_color_real_psnr on a rather difficult sample. Used Chainner v0.19.4 with pytorch on CPU.

Source
![1_scunet_source](https://github.com/chaiNNer-org/chaiNNer/assets/98578859/55232022-19f3-4fe3-82d8-b6feda9ed2fb)

SCUNet GAN
![2_scunet_color_real_gan](https://github.com/chaiNNer-org/chaiNNer/assets/98578859/2cd3dd1b-08aa-4fb7-9a43-392a3a0b7dc9)

SCUNet PSNR
![3_scunet_color_real_psnr](https://github.com/chaiNNer-org/chaiNNer/assets/98578859/98d39731-f849-4af5-a280-13a29a4d245f)

An otherwise almost perfect result (especially the PSNR variance) is ruined by a few areas where the noise remains untreated. I tried the grey variations too but the quality was far worse. This happens to every image, black/white or colour, or less noisy ones.

As a side note, would it be hard to implement support for DRUNet models? I also see impressive results there. They currently have four models as I see here in this model zoo:
https://drive.google.com/drive/folders/13kfr3qny7S2xwG9h7v95F5mkWs0OmU0D

I don't know, any ideas?

**Comment by adegerard** [comment] 2023-08-30 13:05
> 

Your image is so noisy the SCUNet cannot remove such noise.
This is not a bug. (original source code and stable-Diffusion-webui give the same result)

I recommend closing this issue.

@Wurlit would you please create another issue (select `Feature request`) DRUNet integration. Thanks.

**Closed** 2023-08-30 13:23 UTC
