### ISSUE TITLE
Remove imagebackground workflow error

### ISSUE THREAD

**Issue by jiehwa** [chaiNNer-org/chaiNNer#2439] opened 2024-01-06 15:26 UTC
![image](https://github.com/chaiNNer-org/chaiNNer/assets/3799526/6f7c34d4-e693-49b6-8006-b2913fc90945)

[renderer.log](https://github.com/chaiNNer-org/chaiNNer/files/13850173/renderer.log)

[main.log](https://github.com/chaiNNer-org/chaiNNer/files/13850171/main.log)
[main.old.log](https://github.com/chaiNNer-org/chaiNNer/files/13850172/main.old.log)

**Comment by joeyballentine** [comment] 2024-01-06 17:27
> MemoryError

How much RAM does your PC have and how much is in use without chaiNNer running?

**Comment by RunDevelopment** [comment] 2024-04-08 14:36
The logs say this:

```
[2024-01-06 23:17:34 +0800] [INFO] Execution options: {'chaiNNer_onnx': {'gpu_index': '0', 'execution_provider': 'CUDAExecutionProvider', 'onnx_tensorrt_cache': '', 'tensorrt_fp16_mode': True}}
[2024-01-06 23:17:35.956] [error] Could not locate zlibwapi.dll. Please make sure it is in your library path!
[2024-01-06 23:17:40.313] [error] Python subprocess exited with code 3221226505 and signal null
```

And the ONNX options are this:
```json
{
    "gpu_index": "0",
    "execution_provider": "CUDAExecutionProvider",
    "onnx_tensorrt_cache": "",
    "tensorrt_fp16_mode": True,
}
```

Googling this error, I found that [this SO post](https://stackoverflow.com/questions/72356588/could-not-locate-zlibwapi-dll-please-make-sure-it-is-in-your-library-path), which seems to indicate that this error is caused by either an invalid CUDA or TensorRT installation.

In any case, ONNX (or whatever ONNX is using under hood) not finding a DLL is either a bug in the library, a problem with your installed software/drivers, or a misconfiguration of your system. None of those problems are caused by chainner and there is nothing chainner can do to fix them. As such, I'll close this issue now, because it isn't caused by chainner.

**Closed by RunDevelopment** 2024-04-08 14:36 UTC
Labels: bug, ONNX
