### ISSUE TITLE
A node for resolution upscale to ≥300DPI

### ISSUE THREAD

**Issue by wilfwilson-art** [chaiNNer-org/chaiNNer#2243] opened 2023-10-04 10:28 UTC
Forgive me if this already exists but on the forums it seems that nobody really knows whether a resolution node will actually contain the info a printer needs to print at 300DPI or above as this may be more meta information than physical pixels. Upcaling AI art for print-ready files is a huge business at the moment.

I'm running a very efficient iterator which upscales twice, removes pixels from the edge and then adds a white border to compensate, resizes to a given side length, names the resulting upscales according to a text append containing automated pixel dimensions and height in cm and a counter (plus other info), whilst also generating a low res thumbnail. Being able to confidently add a 300DPI res change would be such a timesaver.

I currently have to use GIMP to change all files to 300DPI one at a time as BIMP will not work on my set up for some reason.

Many thanks in advance for your time and reply

Wilf

**Comment by RunDevelopment** [comment] 2023-10-04 12:45
Duplicate of #1754.

The TLDR is that DPI is just image metadata (just like author, camera, geo tag, etc.), and chaiNNer currently doesn't have a way to specify metadata in Save Image.

**Closed** 2023-10-04 12:46 UTC
