### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by li1i9** [chaiNNer-org/chaiNNer#1742] opened 2023-04-17 19:11 UTC
Hey there,
I would like some help regarding ChaiNNer.
I installed ChaiNNer properly.
I installed Automatic1111.
ChaiNNer says "It's connected to Automatic1111"
I'm searching for the text-to-image option on the left side but it's not there.
I'm referring to the example on this page https://github.com/chaiNNer-org/chaiNNer/pull/1500
Again, please help me out, I'm really struggling to find any information on the internet or videos on the matter. I've been searching for days now.

**Comment by joeyballentine** [comment] 2023-04-17 19:15
Make sure you're launching it with the --api flag. For example: `./webui.bat --api`. And make sure you do this before starting chainner.

If it's still not showing up, then there's probably something else wrong going on.

Also FYI you're not really likely to find any info on the internet for troubleshooting chaiNNer as it's not that popular. All that's either going to be on this GitHub page or in the Discord.

**Comment by li1i9** [comment] 2023-04-17 21:34
First, I can't understand how such a great program is not popular. You people did an amazing job on it! It's super intuitive and easy to use. I guess, a bit more youtube videos might help with the popularization.
About the second matter. I am not so much of a programmer so the example you gave me is leading me nowhere.
So please, if you'd be so kind to explain in a bit more detail for someone who is not that versed in programming.
Thanks a lot!

**Comment by joeyballentine** [comment] 2023-04-17 21:48
You have to set this up: https://github.com/AUTOMATIC1111/stable-diffusion-webui. It explains there how to set it up.

I had assumed based on your initial message that you did have it set up. Once you do, you just launch it like normal but add the `--api` flag.

**Comment by li1i9** [comment] 2023-04-17 23:53
Thank you a lot!!! :)

**Comment by RunDevelopment** [comment] 2023-05-07 13:54
I'm going to close this now as the issue seems to have been resolved. If the issue is still relevant, please comment and we'll reopen it.

**Closed by RunDevelopment** 2023-05-07 13:54 UTC
