### ISSUE TITLE
chaiNNer doesn't finish loading

### ISSUE THREAD

**Issue by YarivTawili** [chaiNNer-org/chaiNNer#1694] opened 2023-04-02 13:58 UTC
Hi, I tried both installation and portable (windows), in both cases when the chaiNNer is loading for the first time it got stuck at the end.
Log attached.
Thanks

[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11132371/main.log)

**Comment by joeyballentine** [comment] 2023-04-02 20:57
Hi. This will be fixed in today's release. Sorry about this it was our of our control

**Comment by joeyballentine** [comment] 2023-04-02 21:40
[The update has been released](https://github.com/chaiNNer-org/chaiNNer/releases/tag/v0.18.4). Please let me know if the issue is fixed for you.

**Comment by brezelseppel** [comment] 2023-04-03 11:59
I had the same error, now with 0.18.4 the GUI loads and works fine. Thank you!

**Comment by joeyballentine** [comment] 2023-04-03 13:00
👍

**Closed by joeyballentine** 2023-04-03 13:00 UTC

**Comment by YarivTawili** [comment] 2023-04-03 18:29
Fixed for me too. Thanks!
