### ISSUE TITLE
Image file iterator not compatible with model file iterator

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [chaiNNer-org/chaiNNer#1354] opened 2022-12-05 19:41 UTC
It is impossible to iterate images in the model iterator.
![image](https://user-images.githubusercontent.com/4449851/205727866-9e09c8a0-4b0a-4138-9fac-78d4e53926cf.png)

Or how should I do it?

**Comment by 0x4E69676874466F78** [comment] 2022-12-05 19:42
If you are going to get rid of the current iterators, should I create issues related to them?

**Comment by joeyballentine** [comment] 2022-12-05 19:52
This is by design. We don't support nested iteration.

Our plan for the iterator replacement would essentially allow this, so yeah this isn't something we will be implementing until that rewrite happens.

**Comment by joeyballentine** [comment] 2022-12-07 01:13
Closing this as it is intended.

**Closed by joeyballentine** 2022-12-07 01:13 UTC

**Comment by starkgate** [comment] 2024-01-07 20:38
I would also be interested in such functionality, being able to nest model and image iterators would be really nice.

**Comment by joeyballentine** [comment] 2024-01-07 22:24
@starkgate there's a lot of technical challenge to that. We also would really like to be able to do this - it's just too difficult to implement right now. We only just finished the first portion of our iterator rewrite, which gets us closer to being able to do this, but we're still pretty far away from it. It took over a year to get to this point so it's gonna be a while before being able to do this is a reality.

**Comment by starkgate** [comment] 2024-01-08 08:18
> @starkgate there's a lot of technical challenge to that. We also would really like to be able to do this - it's just too difficult to implement right now. We only just finished the first portion of our iterator rewrite, which gets us closer to being able to do this, but we're still pretty far away from it. It took over a year to get to this point so it's gonna be a while before being able to do this is a reality.

Thanks for the update. What ChaiNNer can do is already amazing (and it looks so neat), I'll be looking forward to the future updates!
